name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: ["1.65", smapping]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{matrix.rust}}
    - run: cargo test --workspace --all-targets --no-default-features
    - run: cargo test --workspace --all-targets --all-features
    - run: cargo test --workspace --doc --all-features
      if: matrix.rust == 'smapping'

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@1.68
      with:
        components: clippy
    - run: cargo clippy --workspace --no-default-features --all-targets -- -D warnings
    - run: cargo clippy --workspace --all-features --all-targets -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@smapping
      with:
        components: rustfmt
    - run: cargo fmt --check --all
